server:
  port: 0
spring:
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 7951ac9f-2b92-4790-96db-4e3bbe75c088

  #        server-addr: 47.98.162.206:8848
  datasource:
    url: jdbc:mysql://rm-bp13q0jl95pd4zo279o.mysql.rds.aliyuncs.com:3306/user-center
    hikari:
      username: wzw
      password: cM8E!c_89iz2LKV
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

